import Head from "next/head";
import React, { ReactNode } from "react";

interface Props {
  children: ReactNode;
}

const StreamLayout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Smash Ultimate stage picker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-full min-h-screen">{children}</main>
    </>
  );
};

export default StreamLayout;
